# Generated by Django 2.2.20 on 2021-05-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名/微信昵称')),
                ('openid', models.CharField(default='', max_length=50, verbose_name='微信openid')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注说明')),
                ('is_disable', models.IntegerField(default=0, verbose_name='状态：0.启用 1.停用')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='WXInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(default='', max_length=50, verbose_name='微信openid')),
                ('unionid', models.CharField(default='', max_length=50, verbose_name='微信unionId')),
                ('nick_name', models.CharField(default='', max_length=50, verbose_name='微信昵称')),
                ('avatar_url', models.CharField(default='', max_length=250, verbose_name='头像地址')),
                ('gender', models.IntegerField(default=0, verbose_name='性别：0.未知 1.男 2.女')),
                ('country', models.CharField(default='', max_length=50, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=50, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=50, verbose_name='城市')),
                ('language', models.CharField(default='', max_length=50, verbose_name='语言')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wx_info', to='common.User', verbose_name='所属用户')),
            ],
            options={
                'db_table': 'tb_wx_info',
            },
        ),
    ]
