# Generated by Django 2.2.20 on 2021-05-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210529_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=200, verbose_name='地址')),
                ('nation', models.CharField(default='', max_length=50, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=50, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=50, verbose_name='城市')),
                ('district', models.CharField(default='', max_length=50, verbose_name='区县')),
                ('street', models.CharField(default='', max_length=50, verbose_name='街道')),
                ('street_number', models.CharField(default='', max_length=50, verbose_name='门牌')),
                ('lng', models.FloatField(default=0, verbose_name='经度')),
                ('lat', models.FloatField(default=0, verbose_name='纬度')),
                ('photo_url', models.CharField(default='', max_length=200, verbose_name='照片地址')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_user', to='common.User', verbose_name='所属用户')),
            ],
            options={
                'db_table': 'tb_sign',
            },
        ),
    ]
