# Generated by Django 2.2.20 on 2021-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=200, verbose_name='照片缩略图地址'),
        ),
    ]
